In [4]:
import numpy as np
vector_row = np.array([[1, -5, 3, 2, 4]])
vector_col = np.array([[1],[2],[3],[4]])
print(vector_row.shape)
print(vector_col.shape)

(1, 5)
(4, 1)


In [15]:
from numpy.linalg import norm
new_vector = vector_row
# print(new_vector)

norm_1 = norm(new_vector, 1)
norm_2 = norm(new_vector, 2)
norm_inf = norm(new_vector, np.inf)

print("L_1 is %.2f"%norm_1)
print("L_2 is %.2f"%norm_2)
print("L_inf is %.2f"%norm_inf)

L_1 is 5.00
L_2 is 7.42
L_inf is 15.00


In [24]:
from numpy import arccos, dot

v = np.array([[10,9,3]])
w = np.array([[2,5,12]])
theta = arccos(dot(v, w.T)/(norm(v)*norm(w)))
print(theta)

[[0.97992471]]
[[ 20  18   6]
 [ 50  45  15]
 [120 108  36]]


In [20]:
v = np.array([[0,2,0]])
w = np.array([[3,0,0]])
print(np.cross(v,w))

[[ 0  0 -6]]


In [25]:
v = np.array([[0,3,2]])
w = np.array([[4,1,1]])
u = np.array([[0,-2,0]])
x = 3*v-2*w+4*u
print(x)

[[-8 -1  4]]


In [49]:
from numpy.linalg import det
from numpy.linalg import inv

M = np.array([[0,2,1,3],
             [3,2,8,1],
             [1,0,0,3],
             [0,3,2,1]])
print("M:\n",M)
print(f"Determinant: {det(M):.2f}")

I = np.eye(4)
print("M*I:\n", np.dot(M,I))

print("M^-1:\n", inv(M))

M:
 [[0 2 1 3]
 [3 2 8 1]
 [1 0 0 3]
 [0 3 2 1]]
Determinant: -38.00
M*I:
 [[0. 2. 1. 3.]
 [3. 2. 8. 1.]
 [1. 0. 0. 3.]
 [0. 3. 2. 1.]]
M^-1:
 [[-1.57894737 -0.07894737  1.23684211  1.10526316]
 [-0.63157895 -0.13157895  0.39473684  0.84210526]
 [ 0.68421053  0.18421053 -0.55263158 -0.57894737]
 [ 0.52631579  0.02631579 -0.07894737 -0.36842105]]


In [57]:
from numpy.linalg import cond, matrix_rank

A = np.array([[1,1,0],
             [0,1,0],
             [1,0,1]])

print(cond(A))
print(matrix_rank(A))
y = np.array([[1],[2],[1]])
A_y = np.concatenate((A, y), axis=1)
print(A_y)

4.048917339522305
3
[[1 1 0 1]
 [0 1 0 2]
 [1 0 1 1]]


In [60]:
u = np.array([[4,3,-5],
             [0,-2.5,2.5],
             [0,0,12]])
l = np.array([[1,0,0],
             [-0.5,1,0],
             [2,-0.8,1]])

print("LU=", np.dot(l,u))


LU= [[ 4.  3. -5.]
 [-2. -4.  5.]
 [ 8.  8.  0.]]


In [88]:
from numpy.linalg import norm

a = np.array([[8,3,-3],
             [-2,-8,5],
             [3,5,-5]])

diag = np.diag(np.abs(a))
off_diag = np.sum(np.abs(a), axis=1) - diag

if np.all(diag > off_diag):
    print("the matrix is diagonally dominant")
else:
    print("the matrix is NOT diagonally dominant")

the matrix is NOT diagonally dominant


In [90]:
y = np.array([14,5,-8])
epsilon = 0.01
converged = False

x_old = np.array([1,1,1])
x1 = x_old[0]
x2 = x_old[1]
x3 = x_old[2]

print("iteration results")
for k in range(1, 50):
    
    x1 = (14-3*x2+3*x3)/8
    x2 = (5+2*x1-5*x3)/(-8)
    x3 = (-8-3*x1-5*x2)/(-5)
    
    x = np.array([x1,x2,x3])
    
    dx = norm(x-x_old)
    dy = norm(y-np.dot(a,x))
    
    print("%d, %.4f, %.4f, %.4f, %.4f"%(k, x[0],x[1],x[2], dy))
    if dx<epsilon :
        converged = True
        print("converged!")
        break
        
    x_old = x
    
if not converged :
    print("Not converged")

iteration results
1, 1.7500, -0.4375, 2.2125, 9.9978
2, 2.7437, 0.0719, 3.3181, 5.8103
3, 2.9673, 0.7070, 4.0874, 3.8674
4, 3.0177, 1.1752, 4.5858, 2.4937
5, 3.0290, 1.4839, 4.9013, 1.5775
6, 3.0315, 1.6804, 5.0993, 0.9903
7, 3.0321, 1.8041, 5.2233, 0.6199
8, 3.0322, 1.8815, 5.3008, 0.3877
9, 3.0322, 1.9300, 5.3493, 0.2424
10, 3.0323, 1.9603, 5.3796, 0.1515
11, 3.0323, 1.9792, 5.3985, 0.0947
12, 3.0323, 1.9910, 5.4104, 0.0592
13, 3.0323, 1.9984, 5.4178, 0.0370
14, 3.0323, 2.0030, 5.4224, 0.0231
converged!


In [102]:
import numpy as np

A = np.array([[4,3,-5],
             [-2,-4,5],
             [8,8,0]])
y = np.array([2,5,-3])
x = np.linalg.solve(A,y)

print("{0}".format(x))

[ 2.20833333 -2.58333333 -0.18333333]


In [104]:
from scipy.linalg import lu

print(lu(A))

(array([[0., 0., 1.],
       [0., 1., 0.],
       [1., 0., 0.]]), array([[ 1.  ,  0.  ,  0.  ],
       [-0.25,  1.  ,  0.  ],
       [ 0.5 ,  0.5 ,  1.  ]]), array([[ 8. ,  8. ,  0. ],
       [ 0. , -2. ,  5. ],
       [ 0. ,  0. , -7.5]]))
